#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-flexmock
Version  : 2.3.0
Release  : 9
URL      : https://rubygems.org/downloads/flexmock-2.3.0.gem
Source0  : https://rubygems.org/downloads/flexmock-2.3.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-coveralls
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubygems-tasks
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-test-unit

%description
# Flex Mock -- Making Mocking Easy
[![Build Status](https://travis-ci.org/doudou/flexmock.svg?branch=master)](https://travis-ci.org/doudou/flexmock)
[![Gem Version](https://badge.fury.io/rb/flexmock.svg)](http://badge.fury.io/rb/flexmock)
[![Coverage Status](https://coveralls.io/repos/doudou/flexmock/badge.svg?branch=master&service=github)](https://coveralls.io/github/doudou/flexmock?branch=master)
[![Documentation](http://b.repl.ca/v1/yard-docs-blue.png)](http://rubydoc.info/gems/flexmock/frames)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n flexmock-2.3.0
gem spec %{SOURCE0} -l --ruby > rubygem-flexmock.gemspec

%build
export LANG=C
gem build rubygem-flexmock.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
flexmock-2.3.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/flexmock-2.3.0
rake --trace test TESTOPTS="-v"
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/flexmock-2.3.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/.autotest
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/.togglerc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/CHANGES
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/GoogleExample.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/examples/rspec_examples_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/examples/test_unit_examples_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/index.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/jamis.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-0.4.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-0.4.1.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-0.4.2.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-0.4.3.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-0.5.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-0.5.1.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-0.6.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-0.6.1.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-0.6.2.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-0.6.3.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-0.6.4.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-0.7.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-0.7.1.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-0.8.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-0.8.2.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-0.8.3.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-0.8.4.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-0.8.5.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-0.9.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-1.0.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-1.0.3.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-1.0.4.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-1.1.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-1.2.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-1.3.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/doc/releases/flexmock-1.3.1.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/flexmock.blurb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/flexmock.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/install.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/argument_matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/argument_matching.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/argument_types.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/call_record.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/call_validator.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/class_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/composite_expectation.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/core.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/core_class_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/default_framework_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/deprecated_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/errors.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/expectation.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/expectation_builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/expectation_director.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/expectation_recorder.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/explicit_needed.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/extensions/active_record_model.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/minitest.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/minitest_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/minitest_integration.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/mock_builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/mock_container.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/noop.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/object_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/ordering.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/partial_mock.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/rails.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/recorder.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/rspec/configure.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/rspec_spy_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/spy_describers.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/symbol_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/test_unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/test_unit_assert_spy_called.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/test_unit_integration.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/test_unit_testcase_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/undefined.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/validators.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/lib/flexmock/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/rakelib/metrics.rake
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/rakelib/preview.rake
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/rakelib/tags.rake
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-2.3.0/todo.txt
/usr/lib64/ruby/gems/2.3.0/specifications/flexmock-2.3.0.gemspec
