#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-flexmock
Version  : 1.3.3
Release  : 6
URL      : https://rubygems.org/downloads/flexmock-1.3.3.gem
Source0  : https://rubygems.org/downloads/flexmock-1.3.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
# Flex Mock -- Making Mocking Easy
FlexMock is a simple, but flexible, mock object library for Ruby unit
testing.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n flexmock-1.3.3
gem spec %{SOURCE0} -l --ruby > rubygem-flexmock.gemspec

%build
gem build rubygem-flexmock.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
flexmock-1.3.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/flexmock-1.3.3
ruby -v -I.:lib:test test*/test_*.rb
ruby -v -I.:lib:test test*/*_test.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/flexmock-1.3.3.gem
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/CHANGES
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/Gemfile.lock
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/README.md
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/GoogleExample.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/examples/rspec_examples_spec.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/examples/test_unit_examples_test.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/index.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-0.4.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-0.4.1.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-0.4.2.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-0.4.3.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-0.5.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-0.5.1.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-0.6.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-0.6.1.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-0.6.2.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-0.6.3.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-0.6.4.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-0.7.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-0.7.1.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-0.8.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-0.8.2.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-0.8.3.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-0.8.4.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-0.8.5.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-0.9.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-1.0.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-1.0.3.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-1.0.4.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-1.1.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-1.2.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-1.3.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/doc/releases/flexmock-1.3.1.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/flexmock.blurb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/install.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/argument_matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/argument_matching.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/argument_types.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/call_record.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/call_validator.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/class_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/composite_expectation.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/core.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/core_class_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/default_framework_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/deprecated_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/errors.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/expectation.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/expectation_builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/expectation_director.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/expectation_recorder.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/explicit_needed.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/extensions/active_record_model.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/mock_builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/mock_container.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/noop.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/object_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/ordering.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/partial_mock.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/rails.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/recorder.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/rspec/configure.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/rspec_spy_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/spy_describers.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/symbol_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/test_unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/test_unit_assert_spy_called.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/test_unit_integration.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/test_unit_testcase_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/undefined.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/validators.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/lib/flexmock/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/aliasing_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/assert_spy_called_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/base_class_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/based_partials_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/container_methods_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/default_framework_adapter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/demeter_mocking_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/deprecated_methods_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/examples_from_readme_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/expectation_description_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/extended_should_receive_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/flexmodel_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/mock_builder_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/naming_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/new_instances_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/object_extensions_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/partial_mock_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/record_mode_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/redirect_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/rspec_integration/integration_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/rspec_integration/spy_example_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/samples_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/should_ignore_missing_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/should_receive_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/spys_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/symbol_extensions_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/test_class_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/test_setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/test_unit_integration/auto_test_unit_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/test_unit_integration/minitest_teardown_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/tu_integration_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/flexmock-1.3.3/test/undefined_test.rb
/usr/lib64/ruby/gems/2.3.0/specifications/flexmock-1.3.3.gemspec
